import { CA_REGIONS, IN_REGIONS, TaxRegion, US_REGIONS, regionsForCountry } from './tax-regions';

export interface CountryPreset {
  countryCode: string;
  label: string;
  currency: string;
  locale: string;
  timezone: string;
  taxLabel: string;
  /** Tax rate in basis points: 500 = 5%. */
  taxRateBp: number;
  /** True where menu prices legally include tax (UK, UAE, AU, IN); false where tax is added at the till (US, CA). */
  taxInclusive: boolean;
  taxNumberLabel: string;
  /** Shown in signup/settings when this market has states, provinces, or GST schemes. */
  regionLabel?: string;
  regions?: TaxRegion[];
}

/**
 * The only country-specific logic in the product. Everything else is market neutral.
 * Rates reflect standard restaurant rates at time of writing; owners can override them in Settings,
 * and the app never gives tax advice.
 */
export const COUNTRY_PRESETS: CountryPreset[] = [
  {
    countryCode: 'AE',
    label: 'United Arab Emirates',
    currency: 'AED',
    locale: 'en-AE',
    timezone: 'Asia/Dubai',
    taxLabel: 'VAT',
    taxRateBp: 500,
    taxInclusive: true,
    taxNumberLabel: 'TRN',
  },
  {
    countryCode: 'SA',
    label: 'Saudi Arabia',
    currency: 'SAR',
    locale: 'en-SA',
    timezone: 'Asia/Riyadh',
    taxLabel: 'VAT',
    taxRateBp: 1500,
    taxInclusive: true,
    taxNumberLabel: 'VAT number',
  },
  {
    countryCode: 'QA',
    label: 'Qatar',
    currency: 'QAR',
    locale: 'en-QA',
    timezone: 'Asia/Qatar',
    taxLabel: 'Tax',
    taxRateBp: 0,
    taxInclusive: true,
    taxNumberLabel: 'Tax ID',
  },
  {
    countryCode: 'GB',
    label: 'United Kingdom',
    currency: 'GBP',
    locale: 'en-GB',
    timezone: 'Europe/London',
    taxLabel: 'VAT',
    taxRateBp: 2000,
    taxInclusive: true,
    taxNumberLabel: 'VAT number',
  },
  {
    countryCode: 'AU',
    label: 'Australia',
    currency: 'AUD',
    locale: 'en-AU',
    timezone: 'Australia/Sydney',
    taxLabel: 'GST',
    taxRateBp: 1000,
    taxInclusive: true,
    taxNumberLabel: 'ABN',
  },
  {
    countryCode: 'CA',
    label: 'Canada',
    currency: 'CAD',
    locale: 'en-CA',
    timezone: 'America/Toronto',
    taxLabel: 'Tax',
    taxRateBp: 1300,
    taxInclusive: false,
    taxNumberLabel: 'GST/HST number',
    regionLabel: 'Province / territory',
    regions: CA_REGIONS,
  },
  {
    countryCode: 'US',
    label: 'United States',
    currency: 'USD',
    locale: 'en-US',
    timezone: 'America/New_York',
    taxLabel: 'Sales tax',
    taxRateBp: 854,
    taxInclusive: false,
    taxNumberLabel: 'Tax ID',
    regionLabel: 'State / city',
    regions: US_REGIONS,
  },
  {
    countryCode: 'IN',
    label: 'India',
    currency: 'INR',
    locale: 'en-IN',
    timezone: 'Asia/Kolkata',
    taxLabel: 'GST',
    taxRateBp: 500,
    taxInclusive: true,
    taxNumberLabel: 'GSTIN',
    regionLabel: 'GST scheme',
    regions: IN_REGIONS,
  },
  {
    countryCode: 'NZ',
    label: 'New Zealand',
    currency: 'NZD',
    locale: 'en-NZ',
    timezone: 'Pacific/Auckland',
    taxLabel: 'GST',
    taxRateBp: 1500,
    taxInclusive: true,
    taxNumberLabel: 'GST number',
  },
  {
    countryCode: 'IE',
    label: 'Ireland',
    currency: 'EUR',
    locale: 'en-IE',
    timezone: 'Europe/Dublin',
    taxLabel: 'VAT',
    taxRateBp: 1350,
    taxInclusive: true,
    taxNumberLabel: 'VAT number',
  },
  {
    countryCode: 'DE',
    label: 'Germany',
    currency: 'EUR',
    locale: 'de-DE',
    timezone: 'Europe/Berlin',
    taxLabel: 'MwSt',
    taxRateBp: 1900,
    taxInclusive: true,
    taxNumberLabel: 'USt-IdNr',
  },
  {
    countryCode: 'FR',
    label: 'France',
    currency: 'EUR',
    locale: 'fr-FR',
    timezone: 'Europe/Paris',
    taxLabel: 'TVA',
    taxRateBp: 1000,
    taxInclusive: true,
    taxNumberLabel: 'TVA',
  },
  {
    countryCode: 'ES',
    label: 'Spain',
    currency: 'EUR',
    locale: 'es-ES',
    timezone: 'Europe/Madrid',
    taxLabel: 'IVA',
    taxRateBp: 1000,
    taxInclusive: true,
    taxNumberLabel: 'NIF',
  },
  {
    countryCode: 'IT',
    label: 'Italy',
    currency: 'EUR',
    locale: 'it-IT',
    timezone: 'Europe/Rome',
    taxLabel: 'IVA',
    taxRateBp: 1000,
    taxInclusive: true,
    taxNumberLabel: 'P.IVA',
  },
  {
    countryCode: 'NL',
    label: 'Netherlands',
    currency: 'EUR',
    locale: 'nl-NL',
    timezone: 'Europe/Amsterdam',
    taxLabel: 'BTW',
    taxRateBp: 900,
    taxInclusive: true,
    taxNumberLabel: 'BTW',
  },
  {
    countryCode: 'MX',
    label: 'Mexico',
    currency: 'MXN',
    locale: 'es-MX',
    timezone: 'America/Mexico_City',
    taxLabel: 'IVA',
    taxRateBp: 1600,
    taxInclusive: true,
    taxNumberLabel: 'RFC',
  },
  {
    countryCode: 'BR',
    label: 'Brazil',
    currency: 'BRL',
    locale: 'pt-BR',
    timezone: 'America/Sao_Paulo',
    taxLabel: 'Tax',
    taxRateBp: 0,
    taxInclusive: true,
    taxNumberLabel: 'CNPJ',
  },
  {
    countryCode: 'ZA',
    label: 'South Africa',
    currency: 'ZAR',
    locale: 'en-ZA',
    timezone: 'Africa/Johannesburg',
    taxLabel: 'VAT',
    taxRateBp: 1500,
    taxInclusive: true,
    taxNumberLabel: 'VAT number',
  },
  {
    countryCode: 'NG',
    label: 'Nigeria',
    currency: 'NGN',
    locale: 'en-NG',
    timezone: 'Africa/Lagos',
    taxLabel: 'VAT',
    taxRateBp: 750,
    taxInclusive: true,
    taxNumberLabel: 'TIN',
  },
  {
    countryCode: 'KE',
    label: 'Kenya',
    currency: 'KES',
    locale: 'en-KE',
    timezone: 'Africa/Nairobi',
    taxLabel: 'VAT',
    taxRateBp: 1600,
    taxInclusive: true,
    taxNumberLabel: 'PIN',
  },
  {
    countryCode: 'PH',
    label: 'Philippines',
    currency: 'PHP',
    locale: 'en-PH',
    timezone: 'Asia/Manila',
    taxLabel: 'VAT',
    taxRateBp: 1200,
    taxInclusive: true,
    taxNumberLabel: 'TIN',
  },
  {
    countryCode: 'MY',
    label: 'Malaysia',
    currency: 'MYR',
    locale: 'en-MY',
    timezone: 'Asia/Kuala_Lumpur',
    taxLabel: 'SST',
    taxRateBp: 800,
    taxInclusive: true,
    taxNumberLabel: 'SST number',
  },
  {
    countryCode: 'ID',
    label: 'Indonesia',
    currency: 'IDR',
    locale: 'id-ID',
    timezone: 'Asia/Jakarta',
    taxLabel: 'PPN',
    taxRateBp: 1100,
    taxInclusive: true,
    taxNumberLabel: 'NPWP',
  },
  {
    countryCode: 'JP',
    label: 'Japan',
    currency: 'JPY',
    locale: 'ja-JP',
    timezone: 'Asia/Tokyo',
    taxLabel: 'Consumption tax',
    taxRateBp: 1000,
    taxInclusive: true,
    taxNumberLabel: 'Tax ID',
  },
  {
    countryCode: 'KR',
    label: 'South Korea',
    currency: 'KRW',
    locale: 'ko-KR',
    timezone: 'Asia/Seoul',
    taxLabel: 'VAT',
    taxRateBp: 1000,
    taxInclusive: true,
    taxNumberLabel: 'Business number',
  },
  {
    countryCode: 'PK',
    label: 'Pakistan',
    currency: 'PKR',
    locale: 'en-PK',
    timezone: 'Asia/Karachi',
    taxLabel: 'GST',
    taxRateBp: 1800,
    taxInclusive: true,
    taxNumberLabel: 'NTN',
  },
  {
    countryCode: 'BD',
    label: 'Bangladesh',
    currency: 'BDT',
    locale: 'en-BD',
    timezone: 'Asia/Dhaka',
    taxLabel: 'VAT',
    taxRateBp: 1500,
    taxInclusive: true,
    taxNumberLabel: 'BIN',
  },
  {
    countryCode: 'SG',
    label: 'Singapore',
    currency: 'SGD',
    locale: 'en-SG',
    timezone: 'Asia/Singapore',
    taxLabel: 'GST',
    taxRateBp: 900,
    taxInclusive: true,
    taxNumberLabel: 'GST number',
  },
  {
    countryCode: 'BH',
    label: 'Bahrain',
    currency: 'BHD',
    locale: 'en-BH',
    timezone: 'Asia/Bahrain',
    taxLabel: 'VAT',
    taxRateBp: 1000,
    taxInclusive: true,
    taxNumberLabel: 'VAT number',
  },
  {
    countryCode: 'KW',
    label: 'Kuwait',
    currency: 'KWD',
    locale: 'en-KW',
    timezone: 'Asia/Kuwait',
    taxLabel: 'Tax',
    taxRateBp: 0,
    taxInclusive: true,
    taxNumberLabel: 'Tax ID',
  },
  {
    countryCode: 'OM',
    label: 'Oman',
    currency: 'OMR',
    locale: 'en-OM',
    timezone: 'Asia/Muscat',
    taxLabel: 'VAT',
    taxRateBp: 500,
    taxInclusive: true,
    taxNumberLabel: 'VAT number',
  },
  {
    countryCode: 'JO',
    label: 'Jordan',
    currency: 'JOD',
    locale: 'en-JO',
    timezone: 'Asia/Amman',
    taxLabel: 'GST',
    taxRateBp: 1600,
    taxInclusive: true,
    taxNumberLabel: 'Tax number',
  },
  {
    countryCode: 'EG',
    label: 'Egypt',
    currency: 'EGP',
    locale: 'en-EG',
    timezone: 'Africa/Cairo',
    taxLabel: 'VAT',
    taxRateBp: 1400,
    taxInclusive: true,
    taxNumberLabel: 'Tax ID',
  },
  {
    countryCode: 'HK',
    label: 'Hong Kong',
    currency: 'HKD',
    locale: 'en-HK',
    timezone: 'Asia/Hong_Kong',
    taxLabel: 'Tax',
    taxRateBp: 0,
    taxInclusive: true,
    taxNumberLabel: 'BRN',
  },
  {
    countryCode: 'GH',
    label: 'Ghana',
    currency: 'GHS',
    locale: 'en-GH',
    timezone: 'Africa/Accra',
    taxLabel: 'VAT',
    taxRateBp: 1500,
    taxInclusive: true,
    taxNumberLabel: 'TIN',
  },
  {
    countryCode: 'JM',
    label: 'Jamaica',
    currency: 'JMD',
    locale: 'en-JM',
    timezone: 'America/Jamaica',
    taxLabel: 'GCT',
    taxRateBp: 1500,
    taxInclusive: true,
    taxNumberLabel: 'TRN',
  },
  {
    countryCode: 'MT',
    label: 'Malta',
    currency: 'EUR',
    locale: 'en-MT',
    timezone: 'Europe/Malta',
    taxLabel: 'VAT',
    taxRateBp: 1800,
    taxInclusive: true,
    taxNumberLabel: 'VAT number',
  },
];

export function resolvePreset(countryCode: string): CountryPreset {
  return (
    COUNTRY_PRESETS.find((p) => p.countryCode === countryCode?.toUpperCase()) ??
    COUNTRY_PRESETS.find((p) => p.countryCode === 'US') ??
    COUNTRY_PRESETS[0]
  );
}

export function presetWithRegions(preset: CountryPreset): CountryPreset {
  return { ...preset, regions: preset.regions ?? regionsForCountry(preset.countryCode) };
}
